[package]
name = "axiom-state"
version = "0.1.0"
edition = "2021"

[dependencies]
axiom-core = { path = "../axiom-core" }
axiom-identity = { path = "../axiom-identity" }
axiom-integrity = { path = "../axiom-integrity" }
bincode = "1.3"
serde = { version = "1.0.228", features = ["derive"] }
