[package]
name = "axiom-boundary"
version = "0.1.0"
edition = "2021"

[dependencies]
axiom-core = { path = "../axiom-core" }
axiom-identity = { path = "../axiom-identity" }
axiom-sanctuary = { path = "../axiom-sanctuary" }
bincode = "1.3"
serde = { version = "1.0.228", features = ["derive"] }